apiVersion: v1
kind: Service
metadata:
  name: myip-entrypoint
  namespace: golang-ns
spec:
  type: NodePort
  selector:
    role: myip
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001